### ISSUE TITLE
experiment with k3os

### ISSUE THREAD

**Issue by billimek** [billimek/homelab-infrastructure#14]
* [k3os](https://github.com/rancher/k3os)

**Comment by billimek** [comment]
After examining the different approaches, decided on the following:

* PXE seems to have too much overhead to be worthwhile for my environment
* cloud-init, while elegant, is only going to be possible for proxmox-based VMs.  I'm planning to move away from proxmox.
* [remastering an ISO](https://github.com/rancher/k3os#remastering-iso) seems to fit well for this case: I can easily provision VMs in proxmox and 'boot from ISO' for bare-metal nodes as necessary

**Comment by billimek** [comment]
Using the [remastering an ISO](https://github.com/rancher/k3os#remastering-iso) approach results in the following:

`grub.cfg` configured as such:

```
set default=0
set timeout=10

set gfxmode=auto
set gfxpayload=keep
insmod all_video
insmod gfxterm

menuentry "k3OS LiveCD & Installer" {
  search.fs_label K3OS root
  set sqfile=/k3os/system/kernel/current/kernel.squashfs
  loopback loop0 /$sqfile
  set root=($root)
  linux (loop0)/vmlinuz printk.devkmsg=on k3os.mode=install k3os.install.device=/dev/sda console=ttyS0 console=tty1 k3os.install.silent=true hostname=k3os-a
  initrd /k3os/system/kernel/current/initrd
}

menuentry "k3OS Rescue Shell" {
  search.fs_label K3OS root
  set sqfile=/k3os/system/kernel/current/kernel.squashfs
  loopback loop0 /$sqfile
  set root=($root)
  linux (loop0)/vmlinuz printk.devkmsg=on rescue console=ttyS0 console=tty1
  initrd /k3os/system/kernel/current/initrd
}
```

Note the `k3os.install.device=/dev/sda` & `hostname=k3os-a` kernel arguments.  The idea is that the _first boot only (from ISO)_ will require setting/changing the hostname to match whatever is desired for the actual node. Subsequent boots will look different and not require this to be dealt with.

---

`config.yaml` configured as such:

```yaml
ssh_authorized_keys:
- github:billimek
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMqgYe/v1r9WHIydNgas3hlXYpdHgPy04ZEYVoZirYpZD/tUuZ5XYzn4LkatRu/lD6YOKISMxRGSV0fEXqFjOQ2Tk+NlgkSOawy/0ED5X/LvI1Sqs39ilFeerKAK0H+ZJfOZzRjlG98QF+0/OFShsHK9JdwmLAH4+wPOzxpwkkXtyVj0mzuFuz84Wpp1uYRpBFp7FRK5pf2wOaZgzu8rdh/zaS3E2vZVYm6gtJuKVfceT0K+IbPdAazKljT9m0xYsXnP0JQCCuxW6GTmVI0dmFSa+VGg0anjUAU0gnm9A9mcOU1NfxigPiEaKjMMFUxtwJQGm8+iYraVsnySzzRQfn jeff@hackintosh.local
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6YYaZvxevdnjTE2Ac5LzgYOXXoVUYX78kPcH2ENMtoiw+438cnlSidYHlC0mMzhmeDAuTS7znpbvgzxknPxTJFOyQnticuzMo2hOTl3xnDMNd1bk38gewm88getY03z2ZymyGfOe/zmJdNZW6SP53c1EHIjiAcb1Cd64FZzpUeiBKQ0dm4D01xFxinnLjU4BmOCKMbN7NSbuAaQtlfaxv9nb/2hjNau5B3kewKFEB3douTCO4VlIIDIq9KXQUUE+aJ/fWTPYB9ymqzahjaRe3e4e1U72J6UB3rxKf3y+R6Y/mj+rYloWGvig2pPJRqCLmNMeeObzwiisPPJCbQ3g5 billimek@github/23922613
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZwZQdLmDKglLw9NYz1SN7+55wTNqCeU2lJN6HQgJ2vyUrpD4T6JcduiH/0aUoUz9vVhfqphwT0hH3O+q/+L1pkCUibiqh4cS9kB46aV5AX5kovcECGa5zaWlGHBepVqitI0J+nmAEQJhsPefaRDLWjJ4CNKODsbtfj+jBNhI9OzMEqR7EDqYu8h6N1KCtqIujxZ/DeumxYsf9ERnjSnRdfekImv9hVojPkDFAj1E3MLfhEfAj6wzZw4bbrqOrssE5K6aK03QEjAULVro2FgAKodFNO8awp0fPb71dzjB2DTlinCYaHSorkwk6w1XJxCMt8jO3nrTth/3+4HzBdaP5 root@proxmox
k3os:
  modules:
  - kvm
  - nvme
  - nfs
  dns_nameservers:
  - 10.0.7.1
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  password: "<redacted>"
  server_url: https://k3s-0:6443
  token: <redacted>
  # labels:
  #   region: us-west-1
  #   somekey: somevalue
  k3s_args:
  - agent
  # - "--disable-agent"
```

This is highly opinionated and specific to my particular configuration.

The resulting patched ISO with these changed files results in a bootable ISO that requires only a one-time setting of the hostname and they will self-provision into the existing k3s cluster.
